const Interface = @This();

arrayOperatorIndex: Child(gd.GDExtensionInterfaceArrayOperatorIndex),
arrayOperatorIndexConst: Child(gd.GDExtensionInterfaceArrayOperatorIndexConst),
arrayRef: Child(gd.GDExtensionInterfaceArrayRef),
arraySetTyped: Child(gd.GDExtensionInterfaceArraySetTyped),
callableCustomCreate2: Child(gd.GDExtensionInterfaceCallableCustomCreate2),
callableCustomCreate: Child(gd.GDExtensionInterfaceCallableCustomCreate),
callableCustomGetUserdata: Child(gd.GDExtensionInterfaceCallableCustomGetUserData),
classdbConstructObject2: Child(gd.GDExtensionInterfaceClassdbConstructObject2),
classdbConstructObject: Child(gd.GDExtensionInterfaceClassdbConstructObject),
classdbGetClassTag: Child(gd.GDExtensionInterfaceClassdbGetClassTag),
classdbGetMethodBind: Child(gd.GDExtensionInterfaceClassdbGetMethodBind),
classdbRegisterExtensionClass2: Child(gd.GDExtensionInterfaceClassdbRegisterExtensionClass2),
classdbRegisterExtensionClass3: Child(gd.GDExtensionInterfaceClassdbRegisterExtensionClass3),
classdbRegisterExtensionClass4: Child(gd.GDExtensionInterfaceClassdbRegisterExtensionClass4),
classdbRegisterExtensionClass: Child(gd.GDExtensionInterfaceClassdbRegisterExtensionClass),
classdbRegisterExtensionClassIntegerConstant: Child(gd.GDExtensionInterfaceClassdbRegisterExtensionClassIntegerConstant),
classdbRegisterExtensionClassMethod: Child(gd.GDExtensionInterfaceClassdbRegisterExtensionClassMethod),
classdbRegisterExtensionClassProperty: Child(gd.GDExtensionInterfaceClassdbRegisterExtensionClassProperty),
classdbRegisterExtensionClassPropertyGroup: Child(gd.GDExtensionInterfaceClassdbRegisterExtensionClassPropertyGroup),
classdbRegisterExtensionClassPropertyIndexed: Child(gd.GDExtensionInterfaceClassdbRegisterExtensionClassPropertyIndexed),
classdbRegisterExtensionClassPropertySubgroup: Child(gd.GDExtensionInterfaceClassdbRegisterExtensionClassPropertySubgroup),
classdbRegisterExtensionClassSignal: Child(gd.GDExtensionInterfaceClassdbRegisterExtensionClassSignal),
classdbRegisterExtensionClassVirtualMethod: Child(gd.GDExtensionInterfaceClassdbRegisterExtensionClassVirtualMethod),
classdbUnregisterExtensionClass: Child(gd.GDExtensionInterfaceClassdbUnregisterExtensionClass),
dictionaryOperatorIndex: Child(gd.GDExtensionInterfaceDictionaryOperatorIndex),
dictionaryOperatorIndexConst: Child(gd.GDExtensionInterfaceDictionaryOperatorIndexConst),
dictionarySetTyped: Child(gd.GDExtensionInterfaceDictionarySetTyped),
editorAddPlugin: Child(gd.GDExtensionInterfaceEditorAddPlugin),
editorHelpLoadXmlFromUtf8Chars: Child(gd.GDExtensionsInterfaceEditorHelpLoadXmlFromUtf8Chars),
editorHelpLoadXmlFromUtf8CharsAndLen: Child(gd.GDExtensionsInterfaceEditorHelpLoadXmlFromUtf8CharsAndLen),
editorRemovePlugin: Child(gd.GDExtensionInterfaceEditorRemovePlugin),
fileAccessGetBuffer: Child(gd.GDExtensionInterfaceFileAccessGetBuffer),
fileAccessStoreBuffer: Child(gd.GDExtensionInterfaceFileAccessStoreBuffer),
getGodotVersion: Child(gd.GDExtensionInterfaceGetGodotVersion),
getLibraryPath: Child(gd.GDExtensionInterfaceGetLibraryPath),
getNativeStructSize: Child(gd.GDExtensionInterfaceGetNativeStructSize),
getVariantFromTypeConstructor: Child(gd.GDExtensionInterfaceGetVariantFromTypeConstructor),
getVariantToTypeConstructor: Child(gd.GDExtensionInterfaceGetVariantToTypeConstructor),
globalGetSingleton: Child(gd.GDExtensionInterfaceGlobalGetSingleton),
imagePtr: Child(gd.GDExtensionInterfaceImagePtr),
imagePtrw: Child(gd.GDExtensionInterfaceImagePtrw),
memAlloc: Child(gd.GDExtensionInterfaceMemAlloc),
memFree: Child(gd.GDExtensionInterfaceMemFree),
memRealloc: Child(gd.GDExtensionInterfaceMemRealloc),
objectCallScriptMethod: Child(gd.GDExtensionInterfaceObjectCallScriptMethod),
objectCastTo: Child(gd.GDExtensionInterfaceObjectCastTo),
objectDestroy: Child(gd.GDExtensionInterfaceObjectDestroy),
objectFreeInstanceBinding: Child(gd.GDExtensionInterfaceObjectFreeInstanceBinding),
objectGetClassName: Child(gd.GDExtensionInterfaceObjectGetClassName),
objectGetInstanceBinding: Child(gd.GDExtensionInterfaceObjectGetInstanceBinding),
objectGetInstanceFromId: Child(gd.GDExtensionInterfaceObjectGetInstanceFromId),
objectGetInstanceId: Child(gd.GDExtensionInterfaceObjectGetInstanceId),
objectGetScriptInstance: Child(gd.GDExtensionInterfaceObjectGetScriptInstance),
objectHasScriptMethod: Child(gd.GDExtensionInterfaceObjectHasScriptMethod),
objectMethodBindCall: Child(gd.GDExtensionInterfaceObjectMethodBindCall),
objectMethodBindPtrcall: Child(gd.GDExtensionInterfaceObjectMethodBindPtrcall),
objectSetInstance: Child(gd.GDExtensionInterfaceObjectSetInstance),
objectSetInstanceBinding: Child(gd.GDExtensionInterfaceObjectSetInstanceBinding),
packedByteArrayOperatorIndex: Child(gd.GDExtensionInterfacePackedByteArrayOperatorIndex),
packedByteArrayOperatorIndexConst: Child(gd.GDExtensionInterfacePackedByteArrayOperatorIndexConst),
packedColorArrayOperatorIndex: Child(gd.GDExtensionInterfacePackedColorArrayOperatorIndex),
packedColorArrayOperatorIndexConst: Child(gd.GDExtensionInterfacePackedColorArrayOperatorIndexConst),
packedFloat32ArrayOperatorIndex: Child(gd.GDExtensionInterfacePackedFloat32ArrayOperatorIndex),
packedFloat32ArrayOperatorIndexConst: Child(gd.GDExtensionInterfacePackedFloat32ArrayOperatorIndexConst),
packedFloat64ArrayOperatorIndex: Child(gd.GDExtensionInterfacePackedFloat64ArrayOperatorIndex),
packedFloat64ArrayOperatorIndexConst: Child(gd.GDExtensionInterfacePackedFloat64ArrayOperatorIndexConst),
packedInt32ArrayOperatorIndex: Child(gd.GDExtensionInterfacePackedInt32ArrayOperatorIndex),
packedInt32ArrayOperatorIndexConst: Child(gd.GDExtensionInterfacePackedInt32ArrayOperatorIndexConst),
packedInt64ArrayOperatorIndex: Child(gd.GDExtensionInterfacePackedInt64ArrayOperatorIndex),
packedInt64ArrayOperatorIndexConst: Child(gd.GDExtensionInterfacePackedInt64ArrayOperatorIndexConst),
packedStringArrayOperatorIndex: Child(gd.GDExtensionInterfacePackedStringArrayOperatorIndex),
packedStringArrayOperatorIndexConst: Child(gd.GDExtensionInterfacePackedStringArrayOperatorIndexConst),
packedVector2ArrayOperatorIndex: Child(gd.GDExtensionInterfacePackedVector2ArrayOperatorIndex),
packedVector2ArrayOperatorIndexConst: Child(gd.GDExtensionInterfacePackedVector2ArrayOperatorIndexConst),
packedVector3ArrayOperatorIndex: Child(gd.GDExtensionInterfacePackedVector3ArrayOperatorIndex),
packedVector3ArrayOperatorIndexConst: Child(gd.GDExtensionInterfacePackedVector3ArrayOperatorIndexConst),
packedVector4ArrayOperatorIndex: Child(gd.GDExtensionInterfacePackedVector4ArrayOperatorIndex),
packedVector4ArrayOperatorIndexConst: Child(gd.GDExtensionInterfacePackedVector4ArrayOperatorIndexConst),
placeholderScriptInstanceCreate: Child(gd.GDExtensionInterfacePlaceHolderScriptInstanceCreate),
placeholderScriptInstanceUpdate: Child(gd.GDExtensionInterfacePlaceHolderScriptInstanceUpdate),
printError: Child(gd.GDExtensionInterfacePrintError),
printErrorWithMessage: Child(gd.GDExtensionInterfacePrintErrorWithMessage),
printScriptError: Child(gd.GDExtensionInterfacePrintScriptError),
printScriptErrorWithMessage: Child(gd.GDExtensionInterfacePrintScriptErrorWithMessage),
printWarning: Child(gd.GDExtensionInterfacePrintWarning),
printWarningWithMessage: Child(gd.GDExtensionInterfacePrintWarningWithMessage),
refGetObject: Child(gd.GDExtensionInterfaceRefGetObject),
refSetObject: Child(gd.GDExtensionInterfaceRefSetObject),
scriptInstanceCreate2: Child(gd.GDExtensionInterfaceScriptInstanceCreate2),
scriptInstanceCreate3: Child(gd.GDExtensionInterfaceScriptInstanceCreate3),
scriptInstanceCreate: Child(gd.GDExtensionInterfaceScriptInstanceCreate),
stringNameNewWithLatin1Chars: Child(gd.GDExtensionInterfaceStringNameNewWithLatin1Chars),
stringNameNewWithUtf8Chars: Child(gd.GDExtensionInterfaceStringNameNewWithUtf8Chars),
stringNameNewWithUtf8CharsAndLen: Child(gd.GDExtensionInterfaceStringNameNewWithUtf8CharsAndLen),
stringNewWithLatin1Chars: Child(gd.GDExtensionInterfaceStringNewWithLatin1Chars),
stringNewWithLatin1CharsAndLen: Child(gd.GDExtensionInterfaceStringNewWithLatin1CharsAndLen),
stringNewWithUtf16Chars: Child(gd.GDExtensionInterfaceStringNewWithUtf16Chars),
stringNewWithUtf16CharsAndLen2: Child(gd.GDExtensionInterfaceStringNewWithUtf16CharsAndLen2),
stringNewWithUtf16CharsAndLen: Child(gd.GDExtensionInterfaceStringNewWithUtf16CharsAndLen),
stringNewWithUtf32Chars: Child(gd.GDExtensionInterfaceStringNewWithUtf32Chars),
stringNewWithUtf32CharsAndLen: Child(gd.GDExtensionInterfaceStringNewWithUtf32CharsAndLen),
stringNewWithUtf8Chars: Child(gd.GDExtensionInterfaceStringNewWithUtf8Chars),
stringNewWithUtf8CharsAndLen2: Child(gd.GDExtensionInterfaceStringNewWithUtf8CharsAndLen2),
stringNewWithUtf8CharsAndLen: Child(gd.GDExtensionInterfaceStringNewWithUtf8CharsAndLen),
stringNewWithWideChars: Child(gd.GDExtensionInterfaceStringNewWithWideChars),
stringNewWithWideCharsAndLen: Child(gd.GDExtensionInterfaceStringNewWithWideCharsAndLen),
stringOperatorIndex: Child(gd.GDExtensionInterfaceStringOperatorIndex),
stringOperatorIndexConst: Child(gd.GDExtensionInterfaceStringOperatorIndexConst),
stringOperatorPlusEqC32Str: Child(gd.GDExtensionInterfaceStringOperatorPlusEqC32str),
stringOperatorPlusEqChar: Child(gd.GDExtensionInterfaceStringOperatorPlusEqChar),
stringOperatorPlusEqCstr: Child(gd.GDExtensionInterfaceStringOperatorPlusEqCstr),
stringOperatorPlusEqString: Child(gd.GDExtensionInterfaceStringOperatorPlusEqString),
stringOperatorPlusEqWcstr: Child(gd.GDExtensionInterfaceStringOperatorPlusEqWcstr),
stringResize: Child(gd.GDExtensionInterfaceStringResize),
stringToLatin1Chars: Child(gd.GDExtensionInterfaceStringToLatin1Chars),
stringToUtf16Chars: Child(gd.GDExtensionInterfaceStringToUtf16Chars),
stringToUtf32Chars: Child(gd.GDExtensionInterfaceStringToUtf32Chars),
stringToUtf8Chars: Child(gd.GDExtensionInterfaceStringToUtf8Chars),
stringToWideChars: Child(gd.GDExtensionInterfaceStringToWideChars),
variantBooleanize: Child(gd.GDExtensionInterfaceVariantBooleanize),
variantCall: Child(gd.GDExtensionInterfaceVariantCall),
variantCallStatic: Child(gd.GDExtensionInterfaceVariantCallStatic),
variantCanConvert: Child(gd.GDExtensionInterfaceVariantCanConvert),
variantCanConvertStrict: Child(gd.GDExtensionInterfaceVariantCanConvertStrict),
variantConstruct: Child(gd.GDExtensionInterfaceVariantConstruct),
variantDestroy: Child(gd.GDExtensionInterfaceVariantDestroy),
variantDuplicate: Child(gd.GDExtensionInterfaceVariantDuplicate),
variantEvaluate: Child(gd.GDExtensionInterfaceVariantEvaluate),
variantGet: Child(gd.GDExtensionInterfaceVariantGet),
variantGetConstantValue: Child(gd.GDExtensionInterfaceVariantGetConstantValue),
variantGetIndexed: Child(gd.GDExtensionInterfaceVariantGetIndexed),
variantGetKeyed: Child(gd.GDExtensionInterfaceVariantGetKeyed),
variantGetNamed: Child(gd.GDExtensionInterfaceVariantGetNamed),
variantGetObjectInstanceId: Child(gd.GDExtensionInterfaceVariantGetObjectInstanceId),
variantGetPtrBuiltinMethod: Child(gd.GDExtensionInterfaceVariantGetPtrBuiltinMethod),
variantGetPtrConstructor: Child(gd.GDExtensionInterfaceVariantGetPtrConstructor),
variantGetPtrDestructor: Child(gd.GDExtensionInterfaceVariantGetPtrDestructor),
variantGetPtrGetter: Child(gd.GDExtensionInterfaceVariantGetPtrGetter),
variantGetPtrIndexedGetter: Child(gd.GDExtensionInterfaceVariantGetPtrIndexedGetter),
variantGetPtrIndexedSetter: Child(gd.GDExtensionInterfaceVariantGetPtrIndexedSetter),
variantGetPtrInternalGetter: Child(gd.GDExtensionInterfaceGetVariantGetInternalPtrFunc),
variantGetPtrKeyedChecker: Child(gd.GDExtensionInterfaceVariantGetPtrKeyedChecker),
variantGetPtrKeyedGetter: Child(gd.GDExtensionInterfaceVariantGetPtrKeyedGetter),
variantGetPtrKeyedSetter: Child(gd.GDExtensionInterfaceVariantGetPtrKeyedSetter),
variantGetPtrOperatorEvaluator: Child(gd.GDExtensionInterfaceVariantGetPtrOperatorEvaluator),
variantGetPtrSetter: Child(gd.GDExtensionInterfaceVariantGetPtrSetter),
variantGetPtrUtilityFunction: Child(gd.GDExtensionInterfaceVariantGetPtrUtilityFunction),
variantGetType: Child(gd.GDExtensionInterfaceVariantGetType),
variantGetTypeName: Child(gd.GDExtensionInterfaceVariantGetTypeName),
variantHasKey: Child(gd.GDExtensionInterfaceVariantHasKey),
variantHasMember: Child(gd.GDExtensionInterfaceVariantHasMember),
variantHasMethod: Child(gd.GDExtensionInterfaceVariantHasMethod),
variantHash: Child(gd.GDExtensionInterfaceVariantHash),
variantHashCompare: Child(gd.GDExtensionInterfaceVariantHashCompare),
variantIterGet: Child(gd.GDExtensionInterfaceVariantIterGet),
variantIterInit: Child(gd.GDExtensionInterfaceVariantIterInit),
variantIterNext: Child(gd.GDExtensionInterfaceVariantIterNext),
variantNewCopy: Child(gd.GDExtensionInterfaceVariantNewCopy),
variantNewNil: Child(gd.GDExtensionInterfaceVariantNewNil),
variantRecursiveHash: Child(gd.GDExtensionInterfaceVariantRecursiveHash),
variantSet: Child(gd.GDExtensionInterfaceVariantSet),
variantSetIndexed: Child(gd.GDExtensionInterfaceVariantSetIndexed),
variantSetKeyed: Child(gd.GDExtensionInterfaceVariantSetKeyed),
variantSetNamed: Child(gd.GDExtensionInterfaceVariantSetNamed),
variantStringify: Child(gd.GDExtensionInterfaceVariantStringify),
workerThreadPoolAddNativeGroupTask: Child(gd.GDExtensionInterfaceWorkerThreadPoolAddNativeGroupTask),
workerThreadPoolAddNativeTask: Child(gd.GDExtensionInterfaceWorkerThreadPoolAddNativeTask),
xmlParserOpenBuffer: Child(gd.GDExtensionInterfaceXmlParserOpenBuffer),

pub fn init(getProcAddress: Child(gd.GDExtensionInterfaceGetProcAddress)) Interface {
    return .{
        .arrayOperatorIndex = @ptrCast(getProcAddress("array_operator_index")),
        .arrayOperatorIndexConst = @ptrCast(getProcAddress("array_operator_index_const")),
        .arrayRef = @ptrCast(getProcAddress("array_ref")),
        .arraySetTyped = @ptrCast(getProcAddress("array_set_typed")),
        .callableCustomCreate = @ptrCast(getProcAddress("callable_custom_create")),
        .callableCustomCreate2 = @ptrCast(getProcAddress("callable_custom_create2")),
        .callableCustomGetUserdata = @ptrCast(getProcAddress("callable_custom_get_userdata")),
        .classdbConstructObject = @ptrCast(getProcAddress("classdb_construct_object")),
        .classdbConstructObject2 = @ptrCast(getProcAddress("classdb_construct_object2")),
        .classdbGetClassTag = @ptrCast(getProcAddress("classdb_get_class_tag")),
        .classdbGetMethodBind = @ptrCast(getProcAddress("classdb_get_method_bind")),
        .classdbRegisterExtensionClass = @ptrCast(getProcAddress("classdb_register_extension_class")),
        .classdbRegisterExtensionClass2 = @ptrCast(getProcAddress("classdb_register_extension_class2")),
        .classdbRegisterExtensionClass3 = @ptrCast(getProcAddress("classdb_register_extension_class3")),
        .classdbRegisterExtensionClass4 = @ptrCast(getProcAddress("classdb_register_extension_class4")),
        .classdbRegisterExtensionClassIntegerConstant = @ptrCast(getProcAddress("classdb_register_extension_class_integer_constant")),
        .classdbRegisterExtensionClassMethod = @ptrCast(getProcAddress("classdb_register_extension_class_method")),
        .classdbRegisterExtensionClassProperty = @ptrCast(getProcAddress("classdb_register_extension_class_property")),
        .classdbRegisterExtensionClassPropertyGroup = @ptrCast(getProcAddress("classdb_register_extension_class_property_group")),
        .classdbRegisterExtensionClassPropertyIndexed = @ptrCast(getProcAddress("classdb_register_extension_class_property_indexed")),
        .classdbRegisterExtensionClassPropertySubgroup = @ptrCast(getProcAddress("classdb_register_extension_class_property_subgroup")),
        .classdbRegisterExtensionClassSignal = @ptrCast(getProcAddress("classdb_register_extension_class_signal")),
        .classdbRegisterExtensionClassVirtualMethod = @ptrCast(getProcAddress("classdb_register_extension_class_virtual_method")),
        .classdbUnregisterExtensionClass = @ptrCast(getProcAddress("classdb_unregister_extension_class")),
        .dictionaryOperatorIndex = @ptrCast(getProcAddress("dictionary_operator_index")),
        .dictionaryOperatorIndexConst = @ptrCast(getProcAddress("dictionary_operator_index_const")),
        .dictionarySetTyped = @ptrCast(getProcAddress("dictionary_set_typed")),
        .editorAddPlugin = @ptrCast(getProcAddress("editor_add_plugin")),
        .editorHelpLoadXmlFromUtf8Chars = @ptrCast(getProcAddress("editor_help_load_xml_from_utf8_chars")),
        .editorHelpLoadXmlFromUtf8CharsAndLen = @ptrCast(getProcAddress("editor_help_load_xml_from_utf8_chars_and_len")),
        .editorRemovePlugin = @ptrCast(getProcAddress("editor_remove_plugin")),
        .fileAccessGetBuffer = @ptrCast(getProcAddress("file_access_get_buffer")),
        .fileAccessStoreBuffer = @ptrCast(getProcAddress("file_access_store_buffer")),
        .getGodotVersion = @ptrCast(getProcAddress("get_godot_version")),
        .getLibraryPath = @ptrCast(getProcAddress("get_library_path")),
        .getNativeStructSize = @ptrCast(getProcAddress("get_native_struct_size")),
        .getVariantFromTypeConstructor = @ptrCast(getProcAddress("get_variant_from_type_constructor")),
        .getVariantToTypeConstructor = @ptrCast(getProcAddress("get_variant_to_type_constructor")),
        .globalGetSingleton = @ptrCast(getProcAddress("global_get_singleton")),
        .imagePtr = @ptrCast(getProcAddress("image_ptr")),
        .imagePtrw = @ptrCast(getProcAddress("image_ptrw")),
        .memAlloc = @ptrCast(getProcAddress("mem_alloc")),
        .memFree = @ptrCast(getProcAddress("mem_free")),
        .memRealloc = @ptrCast(getProcAddress("mem_realloc")),
        .objectCallScriptMethod = @ptrCast(getProcAddress("object_call_script_method")),
        .objectCastTo = @ptrCast(getProcAddress("object_cast_to")),
        .objectDestroy = @ptrCast(getProcAddress("object_destroy")),
        .objectFreeInstanceBinding = @ptrCast(getProcAddress("object_free_instance_binding")),
        .objectGetClassName = @ptrCast(getProcAddress("object_get_class_name")),
        .objectGetInstanceBinding = @ptrCast(getProcAddress("object_get_instance_binding")),
        .objectGetInstanceFromId = @ptrCast(getProcAddress("object_get_instance_from_id")),
        .objectGetInstanceId = @ptrCast(getProcAddress("object_get_instance_id")),
        .objectGetScriptInstance = @ptrCast(getProcAddress("object_get_script_instance")),
        .objectHasScriptMethod = @ptrCast(getProcAddress("object_has_script_method")),
        .objectMethodBindCall = @ptrCast(getProcAddress("object_method_bind_call")),
        .objectMethodBindPtrcall = @ptrCast(getProcAddress("object_method_bind_ptrcall")),
        .objectSetInstance = @ptrCast(getProcAddress("object_set_instance")),
        .objectSetInstanceBinding = @ptrCast(getProcAddress("object_set_instance_binding")),
        .packedByteArrayOperatorIndex = @ptrCast(getProcAddress("packed_byte_array_operator_index")),
        .packedByteArrayOperatorIndexConst = @ptrCast(getProcAddress("packed_byte_array_operator_index_const")),
        .packedColorArrayOperatorIndex = @ptrCast(getProcAddress("packed_color_array_operator_index")),
        .packedColorArrayOperatorIndexConst = @ptrCast(getProcAddress("packed_color_array_operator_index_const")),
        .packedFloat32ArrayOperatorIndex = @ptrCast(getProcAddress("packed_float32_array_operator_index")),
        .packedFloat32ArrayOperatorIndexConst = @ptrCast(getProcAddress("packed_float32_array_operator_index_const")),
        .packedFloat64ArrayOperatorIndex = @ptrCast(getProcAddress("packed_float64_array_operator_index")),
        .packedFloat64ArrayOperatorIndexConst = @ptrCast(getProcAddress("packed_float64_array_operator_index_const")),
        .packedInt32ArrayOperatorIndex = @ptrCast(getProcAddress("packed_int32_array_operator_index")),
        .packedInt32ArrayOperatorIndexConst = @ptrCast(getProcAddress("packed_int32_array_operator_index_const")),
        .packedInt64ArrayOperatorIndex = @ptrCast(getProcAddress("packed_int64_array_operator_index")),
        .packedInt64ArrayOperatorIndexConst = @ptrCast(getProcAddress("packed_int64_array_operator_index_const")),
        .packedStringArrayOperatorIndex = @ptrCast(getProcAddress("packed_string_array_operator_index")),
        .packedStringArrayOperatorIndexConst = @ptrCast(getProcAddress("packed_string_array_operator_index_const")),
        .packedVector2ArrayOperatorIndex = @ptrCast(getProcAddress("packed_vector2_array_operator_index")),
        .packedVector2ArrayOperatorIndexConst = @ptrCast(getProcAddress("packed_vector2_array_operator_index_const")),
        .packedVector3ArrayOperatorIndex = @ptrCast(getProcAddress("packed_vector3_array_operator_index")),
        .packedVector3ArrayOperatorIndexConst = @ptrCast(getProcAddress("packed_vector3_array_operator_index_const")),
        .packedVector4ArrayOperatorIndex = @ptrCast(getProcAddress("packed_vector4_array_operator_index")),
        .packedVector4ArrayOperatorIndexConst = @ptrCast(getProcAddress("packed_vector4_array_operator_index_const")),
        .placeholderScriptInstanceCreate = @ptrCast(getProcAddress("placeholder_script_instance_create")),
        .placeholderScriptInstanceUpdate = @ptrCast(getProcAddress("placeholder_script_instance_update")),
        .printError = @ptrCast(getProcAddress("print_error")),
        .printErrorWithMessage = @ptrCast(getProcAddress("print_error_with_message")),
        .printScriptError = @ptrCast(getProcAddress("print_script_error")),
        .printScriptErrorWithMessage = @ptrCast(getProcAddress("print_script_error_with_message")),
        .printWarning = @ptrCast(getProcAddress("print_warning")),
        .printWarningWithMessage = @ptrCast(getProcAddress("print_warning_with_message")),
        .refGetObject = @ptrCast(getProcAddress("ref_get_object")),
        .refSetObject = @ptrCast(getProcAddress("ref_set_object")),
        .scriptInstanceCreate = @ptrCast(getProcAddress("script_instance_create")),
        .scriptInstanceCreate2 = @ptrCast(getProcAddress("script_instance_create2")),
        .scriptInstanceCreate3 = @ptrCast(getProcAddress("script_instance_create3")),
        .stringNameNewWithLatin1Chars = @ptrCast(getProcAddress("string_name_new_with_latin1_chars")),
        .stringNameNewWithUtf8Chars = @ptrCast(getProcAddress("string_name_new_with_utf8_chars")),
        .stringNameNewWithUtf8CharsAndLen = @ptrCast(getProcAddress("string_name_new_with_utf8_chars_and_len")),
        .stringNewWithLatin1Chars = @ptrCast(getProcAddress("string_new_with_latin1_chars")),
        .stringNewWithLatin1CharsAndLen = @ptrCast(getProcAddress("string_new_with_latin1_chars_and_len")),
        .stringNewWithUtf16Chars = @ptrCast(getProcAddress("string_new_with_utf16_chars")),
        .stringNewWithUtf16CharsAndLen = @ptrCast(getProcAddress("string_new_with_utf16_chars_and_len")),
        .stringNewWithUtf16CharsAndLen2 = @ptrCast(getProcAddress("string_new_with_utf16_chars_and_len2")),
        .stringNewWithUtf32Chars = @ptrCast(getProcAddress("string_new_with_utf32_chars")),
        .stringNewWithUtf32CharsAndLen = @ptrCast(getProcAddress("string_new_with_utf32_chars_and_len")),
        .stringNewWithUtf8Chars = @ptrCast(getProcAddress("string_new_with_utf8_chars")),
        .stringNewWithUtf8CharsAndLen = @ptrCast(getProcAddress("string_new_with_utf8_chars_and_len")),
        .stringNewWithUtf8CharsAndLen2 = @ptrCast(getProcAddress("string_new_with_utf8_chars_and_len2")),
        .stringNewWithWideChars = @ptrCast(getProcAddress("string_new_with_wide_chars")),
        .stringNewWithWideCharsAndLen = @ptrCast(getProcAddress("string_new_with_wide_chars_and_len")),
        .stringOperatorIndex = @ptrCast(getProcAddress("string_operator_index")),
        .stringOperatorIndexConst = @ptrCast(getProcAddress("string_operator_index_const")),
        .stringOperatorPlusEqC32Str = @ptrCast(getProcAddress("string_operator_plus_eq_c32str")),
        .stringOperatorPlusEqChar = @ptrCast(getProcAddress("string_operator_plus_eq_char")),
        .stringOperatorPlusEqCstr = @ptrCast(getProcAddress("string_operator_plus_eq_cstr")),
        .stringOperatorPlusEqString = @ptrCast(getProcAddress("string_operator_plus_eq_string")),
        .stringOperatorPlusEqWcstr = @ptrCast(getProcAddress("string_operator_plus_eq_wcstr")),
        .stringResize = @ptrCast(getProcAddress("string_resize")),
        .stringToLatin1Chars = @ptrCast(getProcAddress("string_to_latin1_chars")),
        .stringToUtf16Chars = @ptrCast(getProcAddress("string_to_utf16_chars")),
        .stringToUtf32Chars = @ptrCast(getProcAddress("string_to_utf32_chars")),
        .stringToUtf8Chars = @ptrCast(getProcAddress("string_to_utf8_chars")),
        .stringToWideChars = @ptrCast(getProcAddress("string_to_wide_chars")),
        .variantBooleanize = @ptrCast(getProcAddress("variant_booleanize")),
        .variantCall = @ptrCast(getProcAddress("variant_call")),
        .variantCallStatic = @ptrCast(getProcAddress("variant_call_static")),
        .variantCanConvert = @ptrCast(getProcAddress("variant_can_convert")),
        .variantCanConvertStrict = @ptrCast(getProcAddress("variant_can_convert_strict")),
        .variantConstruct = @ptrCast(getProcAddress("variant_construct")),
        .variantDestroy = @ptrCast(getProcAddress("variant_destroy")),
        .variantDuplicate = @ptrCast(getProcAddress("variant_duplicate")),
        .variantEvaluate = @ptrCast(getProcAddress("variant_evaluate")),
        .variantGet = @ptrCast(getProcAddress("variant_get")),
        .variantGetConstantValue = @ptrCast(getProcAddress("variant_get_constant_value")),
        .variantGetIndexed = @ptrCast(getProcAddress("variant_get_indexed")),
        .variantGetKeyed = @ptrCast(getProcAddress("variant_get_keyed")),
        .variantGetNamed = @ptrCast(getProcAddress("variant_get_named")),
        .variantGetObjectInstanceId = @ptrCast(getProcAddress("variant_get_object_instance_id")),
        .variantGetPtrBuiltinMethod = @ptrCast(getProcAddress("variant_get_ptr_builtin_method")),
        .variantGetPtrConstructor = @ptrCast(getProcAddress("variant_get_ptr_constructor")),
        .variantGetPtrDestructor = @ptrCast(getProcAddress("variant_get_ptr_destructor")),
        .variantGetPtrGetter = @ptrCast(getProcAddress("variant_get_ptr_getter")),
        .variantGetPtrIndexedGetter = @ptrCast(getProcAddress("variant_get_ptr_indexed_getter")),
        .variantGetPtrIndexedSetter = @ptrCast(getProcAddress("variant_get_ptr_indexed_setter")),
        .variantGetPtrInternalGetter = @ptrCast(getProcAddress("variant_get_ptr_internal_getter")),
        .variantGetPtrKeyedChecker = @ptrCast(getProcAddress("variant_get_ptr_keyed_checker")),
        .variantGetPtrKeyedGetter = @ptrCast(getProcAddress("variant_get_ptr_keyed_getter")),
        .variantGetPtrKeyedSetter = @ptrCast(getProcAddress("variant_get_ptr_keyed_setter")),
        .variantGetPtrOperatorEvaluator = @ptrCast(getProcAddress("variant_get_ptr_operator_evaluator")),
        .variantGetPtrSetter = @ptrCast(getProcAddress("variant_get_ptr_setter")),
        .variantGetPtrUtilityFunction = @ptrCast(getProcAddress("variant_get_ptr_utility_function")),
        .variantGetType = @ptrCast(getProcAddress("variant_get_type")),
        .variantGetTypeName = @ptrCast(getProcAddress("variant_get_type_name")),
        .variantHasKey = @ptrCast(getProcAddress("variant_has_key")),
        .variantHasMember = @ptrCast(getProcAddress("variant_has_member")),
        .variantHasMethod = @ptrCast(getProcAddress("variant_has_method")),
        .variantHash = @ptrCast(getProcAddress("variant_hash")),
        .variantHashCompare = @ptrCast(getProcAddress("variant_hash_compare")),
        .variantIterGet = @ptrCast(getProcAddress("variant_iter_get")),
        .variantIterInit = @ptrCast(getProcAddress("variant_iter_init")),
        .variantIterNext = @ptrCast(getProcAddress("variant_iter_next")),
        .variantNewCopy = @ptrCast(getProcAddress("variant_new_copy")),
        .variantNewNil = @ptrCast(getProcAddress("variant_new_nil")),
        .variantRecursiveHash = @ptrCast(getProcAddress("variant_recursive_hash")),
        .variantSet = @ptrCast(getProcAddress("variant_set")),
        .variantSetIndexed = @ptrCast(getProcAddress("variant_set_indexed")),
        .variantSetKeyed = @ptrCast(getProcAddress("variant_set_keyed")),
        .variantSetNamed = @ptrCast(getProcAddress("variant_set_named")),
        .variantStringify = @ptrCast(getProcAddress("variant_stringify")),
        .workerThreadPoolAddNativeGroupTask = @ptrCast(getProcAddress("worker_thread_pool_add_native_group_task")),
        .workerThreadPoolAddNativeTask = @ptrCast(getProcAddress("worker_thread_pool_add_native_task")),
        .xmlParserOpenBuffer = @ptrCast(getProcAddress("xml_parser_open_buffer")),
    };
}

const std = @import("std");
const gd = @import("godot");

const Child = std.meta.Child;
